"""
健康检查常量定义
"""

# 健康状态常量
HEALTH_STATUS_HEALTHY = "healthy"
HEALTH_STATUS_UNHEALTHY = "unhealthy"
HEALTH_STATUS_DEGRADED = "degraded"
HEALTH_STATUS_UNKNOWN = "unknown"

# 健康检查间隔（秒）
HEALTH_CHECK_INTERVAL = 30
HEALTH_CHECK_TIMEOUT = 5

# 阈值
HEALTH_MEMORY_THRESHOLD = 0.85  # 85%
HEALTH_CPU_THRESHOLD = 0.80  # 80%
HEALTH_DISK_THRESHOLD = 0.90  # 90%

__all__ = [
    'HEALTH_STATUS_HEALTHY',
    'HEALTH_STATUS_UNHEALTHY',
    'HEALTH_STATUS_DEGRADED',
    'HEALTH_STATUS_UNKNOWN',
    'HEALTH_CHECK_INTERVAL',
    'HEALTH_CHECK_TIMEOUT',
    'HEALTH_MEMORY_THRESHOLD',
    'HEALTH_CPU_THRESHOLD',
    'HEALTH_DISK_THRESHOLD'
]
