"""
健康检查组件模块
"""

from ..constants import (
    HEALTH_STATUS_HEALTHY,
    HEALTH_STATUS_UNHEALTHY,
    HEALTH_STATUS_DEGRADED,
    HEALTH_STATUS_UNKNOWN
)

__all__ = [
    'HEALTH_STATUS_HEALTHY',
    'HEALTH_STATUS_UNHEALTHY',
    'HEALTH_STATUS_DEGRADED',
    'HEALTH_STATUS_UNKNOWN'
]

