"""
集成层接口模块
"""

# 从foundation.interfaces导入核心接口
try:
    from src.core.foundation.interfaces.core_interfaces import (
        ICoreComponent,
        IEventBus,
        IDependencyContainer,
        IBusinessProcessOrchestrator,
        ILayerInterface
    )
    # ILayerComponent 在本地 interfaces.py 中定义
    from .interfaces import ILayerComponent
    # 从interfaces模块导入组件管理器接口和适配器接口
    from .interfaces import (
        IComponentManager, IInterfaceManager, LayerInterfaceManager, CoreLayerInterface,
        create_layer_interface_manager, create_core_layer_interface, validate_component_interface,
        IBusinessAdapter, IAdapterComponent, IServiceBridge, IFallbackService
    )
except ImportError:
        # 如果 interfaces.py 中没有，使用 Protocol 定义
        from typing import Protocol, Dict, Any
        class IBusinessAdapter(Protocol):
            """业务适配器接口"""
            def adapt_request(self, request: Dict[str, Any]) -> Dict[str, Any]: ...
            def adapt_response(self, response: Dict[str, Any]) -> Dict[str, Any]: ...
        
        class IAdapterComponent(Protocol):
            """适配器组件接口"""
            def transform(self, data: Any) -> Any: ...
            def validate(self, data: Any) -> bool: ...
        
        class IServiceBridge(Protocol):
            """服务桥接接口"""
            def connect(self, source: str, target: str) -> bool: ...
            def disconnect(self, source: str, target: str) -> bool: ...
            def transfer(self, data: Any, source: str, target: str) -> Any: ...
        
        class IFallbackService(Protocol):
            """降级服务接口"""
            def enable_fallback(self) -> bool: ...
            def disable_fallback(self) -> bool: ...
            def get_fallback_status(self) -> Dict[str, Any]: ...
except ImportError:
    # 提供Protocol定义
    from typing import Protocol, Dict, Any, List, Optional

    class ICoreComponent(Protocol):
        """核心组件接口"""
        def get_status(self) -> Any: ...
        def health_check(self) -> Dict[str, Any]: ...

    class IEventBus(Protocol):
        """事件总线接口"""
        def publish(self, event_type: str, data: Dict[str, Any]) -> bool: ...

    class IDependencyContainer(Protocol):
        """依赖容器接口"""
        def register_service(self, service: Any) -> None: ...
        def get_service(self, service_type: Any) -> Any: ...

    class ILayerComponent(Protocol):
        """层组件接口"""
        def initialize(self) -> bool: ...
        def start(self) -> bool: ...
        def stop(self) -> bool: ...
        def get_status(self) -> Dict[str, Any]: ...
        def health_check(self) -> Dict[str, Any]: ...
        def resolve(self, name: str) -> Any: ...

    class IBusinessProcessOrchestrator(Protocol):
        """业务流程编排器接口"""
        def start_process(self, name: str, context: Dict[str, Any]) -> str: ...

    class ILayerInterface(Protocol):
        """层间接口"""
        def communicate_up(self, message: Dict[str, Any]) -> Dict[str, Any]: ...

    class IServiceComponent(Protocol):
        """服务组件接口"""
        def start(self) -> bool: ...
        def stop(self) -> bool: ...
        def get_status(self) -> Dict[str, Any]: ...
        def health_check(self) -> Dict[str, Any]: ...

    class ILayerComponent(Protocol):
        """层组件接口"""
        def initialize(self) -> bool: ...
        def start(self) -> bool: ...
        def stop(self) -> bool: ...
        def get_status(self) -> Dict[str, Any]: ...
        def health_check(self) -> Dict[str, Any]: ...

    class IBusinessAdapter(Protocol):
        """业务适配器接口"""
        def adapt_request(self, request: Dict[str, Any]) -> Dict[str, Any]: ...
        def adapt_response(self, response: Dict[str, Any]) -> Dict[str, Any]: ...

    class IAdapterComponent(Protocol):
        """适配器组件接口"""
        def transform(self, data: Any) -> Any: ...
        def validate(self, data: Any) -> bool: ...

    class IServiceBridge(Protocol):
        """服务桥接接口"""
        def connect(self, source: str, target: str) -> bool: ...
        def disconnect(self, source: str, target: str) -> bool: ...
        def transfer(self, data: Any, source: str, target: str) -> Any: ...

# IServiceComponent不存在于core_interfaces中，移除此导入

    class IComponentManager(Protocol):
        """组件管理器接口"""
        def register_component(self, component: Any) -> bool: ...
        def unregister_component(self, component_id: str) -> bool: ...
        def get_component(self, component_id: str) -> Any: ...
        def list_components(self) -> List[Any]: ...

    class IInterfaceManager(Protocol):
        """接口管理器"""
        def register_interface(self, name: str, interface: Any) -> bool: ...
        def get_interface(self, name: str) -> Any: ...

    class LayerInterfaceManager(Protocol):
        """层接口管理器协议"""
        def register_method(self, method_name: str, method_func: Any) -> None: ...
        def register_interface(self, interface_name: str, interface_obj: Any) -> None: ...
        def register_component(self, component_name: str, component: Any) -> None: ...
        def get_method(self, method_name: str) -> Any: ...
        def get_interface(self, interface_name: str) -> Any: ...
        def get_component(self, component_name: str) -> Any: ...

    class CoreLayerInterface(Protocol):
        """核心层接口协议"""
        def initialize(self) -> bool: ...
        def process(self, data: Any) -> Any: ...
        def validate_config(self) -> bool: ...
        def get_status(self) -> Dict[str, Any]: ...
        def get_layer_type(self) -> Any: ...
        def health_check(self) -> Dict[str, Any]: ...

    def create_layer_interface_manager(layer_name: str) -> Any:
        """创建层接口管理器（协议实现）"""
        raise RuntimeError("LayerInterfaceManager not available") from None

    def create_core_layer_interface(config: Optional[Dict[str, Any]] = None) -> Any:
        """创建核心层接口（协议实现）"""
        raise RuntimeError("CoreLayerInterface not available") from None

    def validate_component_interface(component: Any) -> Dict[str, Any]:
        """验证组件接口（协议实现）"""
        return {'valid': False, 'errors': ['Component interface validation not available']}

    class IFallbackService(Protocol):
        """降级服务接口"""
        def enable_fallback(self) -> bool: ...
        def disable_fallback(self) -> bool: ...
        def get_fallback_status(self) -> Dict[str, Any]: ...

__all__ = [
    'ICoreComponent',
    'IEventBus',
    'IDependencyContainer',
    'IBusinessProcessOrchestrator',
    'ILayerInterface',
    'IServiceComponent',
    'ILayerComponent',
    'IBusinessAdapter',
    'IAdapterComponent',
    'IServiceBridge',
    'IFallbackService',
    'IComponentManager',
    'IInterfaceManager',
    'LayerInterfaceManager',
    'CoreLayerInterface',
    'create_layer_interface_manager',
    'create_core_layer_interface',
    'validate_component_interface'
]

