cluster.name: rqa2025-cluster
discovery.type: single-node
http.port: 9200
network.host: localhost
node.name: rqa2025-node-1
path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch
xpack.security.authc.api_key.enabled: 'true'
xpack.security.enabled: 'true'
