elasticsearch.hosts:
- http://localhost:9200
elasticsearch.password: changeme
elasticsearch.username: elastic
server.host: localhost
server.port: 5601
xpack.security.enabled: 'true'
xpack.security.encryptionKey: changeme
