"""
系统常量模块（顶层别名）
提供向后兼容的导入路径
"""

# 从core.constants导入所有常量
from src.core.constants import *

# 添加自动化相关常量
MAX_CONCURRENT_TASKS = 10
DEFAULT_TASK_TIMEOUT = 30.0
DEPLOYMENT_TIMEOUT = 60.0
HEALTH_CHECK_INTERVAL = 60.0
NOTIFICATION_RETRY_LIMIT = 3
ALERT_COOLDOWN_SECONDS = 300
RULE_CACHE_SIZE = 1000
RULE_PROCESSING_TIMEOUT = 10.0
MAX_RULES_PER_WORKFLOW = 100

__all__ = [
    'CoreConstants',
    'DEFAULT_TIMEOUT',
    'MAX_RETRIES',
    'RETRY_DELAY',
    'DEFAULT_BATCH_SIZE',
    'MIN_CONNECTIONS',
    'MAX_CONNECTIONS',
    'MAX_BATCH_SIZE',
    'DEFAULT_CACHE_TTL',
    'API_RESPONSE_ACCEPTABLE',
    'SECONDS_PER_MINUTE',
    'SECONDS_PER_HOUR',
    'MINUTES_PER_HOUR',
    'MAX_CONCURRENT_TASKS',
    'DEFAULT_TASK_TIMEOUT',
    'DEPLOYMENT_TIMEOUT',
    'HEALTH_CHECK_INTERVAL',
    'NOTIFICATION_RETRY_LIMIT',
    'ALERT_COOLDOWN_SECONDS',
]

