name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: '3.9'

    - name: Create conda environment
      run: |
        conda create -n rqa python=3.9 -y
        conda activate rqa
        conda install -c conda-forge pytest pytest-cov pytest-mock -y

    - name: Install dependencies
      run: |
        conda activate rqa
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install apscheduler pytest-cov pytest-mock

    - name: Run unit tests
      run: |
        conda activate rqa
        python -m pytest tests/unit/ -v --cov=src --cov-report=xml --cov-report=html

    - name: Run infrastructure integration tests
      run: |
        conda activate rqa
        python -m pytest tests/integration/test_infrastructure_integration.py -v --cov=src/infrastructure --cov-append

    - name: Run model inference integration tests
      run: |
        conda activate rqa
        python -m pytest tests/integration/test_model_inference_integration.py -v --cov=src/models --cov-append

    - name: Run backtest integration tests
      run: |
        conda activate rqa
        python -m pytest tests/integration/test_backtest_integration.py -v --cov=src/backtest --cov-append

    - name: Run trading integration tests
      run: |
        conda activate rqa
        python -m pytest tests/integration/test_trading_integration.py -v --cov=src/trading --cov-append

    - name: Run advanced trading integration tests
      run: |
        conda activate rqa
        python -m pytest tests/integration/test_trading_advanced_integration.py -v --cov=src/trading --cov-append

    - name: Check test hooks
      run: |
        conda activate rqa
        python scripts/test_hooks_checker.py --project-root . --coverage

    - name: Validate test structure
      run: |
        conda activate rqa
        python scripts/check_test_structure.py

    - name: Generate coverage report
      run: |
        conda activate rqa
        python -m pytest --cov=src --cov-report=html --cov-report=xml --cov-report=term-missing

    - name: Upload coverage reports
      uses: actions/upload-artifact@v3
      with:
        name: coverage-reports
        path: |
          htmlcov/
          coverage.xml
          test_hooks_report.md

    - name: Check coverage threshold
      run: |
        conda activate rqa
        python -m pytest --cov=src --cov-fail-under=70
