name: Test Hooks Check

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/infrastructure/**'
      - 'tests/unit/infrastructure/**'
      - 'scripts/test_hooks_checker.py'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'src/infrastructure/**'
      - 'tests/unit/infrastructure/**'
      - 'scripts/test_hooks_checker.py'

jobs:
  test-hooks-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: '3.9'
        
    - name: Create conda environment
      run: |
        conda create -n rqa python=3.9 -y
        conda activate rqa
        conda install -c conda-forge pytest pytest-cov ast -y
        
    - name: Install dependencies
      run: |
        conda activate rqa
        python -m pip install --upgrade pip
        pip install pytest pytest-cov ast
        
    - name: Run test hooks checker
      run: |
        conda activate rqa
        python scripts/test_hooks_checker.py --project-root . --output test_hooks_report.md
        
    - name: Upload report
      uses: actions/upload-artifact@v3
      with:
        name: test-hooks-report
        path: test_hooks_report.md
        
    - name: Check coverage
      run: |
        conda activate rqa
        python scripts/test_hooks_checker.py --project-root . --coverage
        
  infrastructure-tests:
    runs-on: ubuntu-latest
    needs: test-hooks-check
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: '3.9'
        
    - name: Create conda environment
      run: |
        conda create -n rqa python=3.9 -y
        conda activate rqa
        conda install -c conda-forge pytest pytest-cov -y
        
    - name: Install dependencies
      run: |
        conda activate rqa
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        
    - name: Run infrastructure tests
      run: |
        conda activate rqa
        python -m pytest tests/unit/infrastructure/ -v --cov=src/infrastructure --cov-report=xml --cov-report=html
        
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: htmlcov/
        
    - name: Upload coverage XML
      uses: actions/upload-artifact@v3
      with:
        name: coverage-xml
        path: coverage.xml 